### ISSUE TITLE
Classification Task on different datasets.

### ISSUE THREAD

**Issue by moushuai** [intel-isl/MultiObjectiveOptimization#1]
Hi, if I use different datasets to each task. Does this algorithm still works? e.g.  Three classification tasks on datasets MNIST, ImageNet, Celebra, using multi objective optimization method proposed in your paper. Can I get better performances both on these three classification tasks?

**Comment by ozansener** [comment]
Hello,

Algorithmically, the original method (MGDA) will work when you have different datasets. However, our faster version (MGDA-UB) will not work since it requires input images to be same. So, you can use MGDA. You will need to set `use_approximation` to `false` and change the code little bit to support different datasets.

On the other hand, better performance is likely but we never experimented on it. So, it is hard to say anything without trying. My intuitive answer is; if tasks are similar enough, it should help. Please let us know if you try it.

**Comment by moushuai** [comment]
Thanks to your quick reply. I will try it latter.：)
